services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ZenAdmin
      POSTGRES_PASSWORD: temp
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5447:5432'
volumes:
  postgres:
